//! **PBKDF2-HMAC-SHA-512**, RFC 8018 section 5.2 over the HMAC in `hmac.rs`.
//! Step 2 of `docs/roadmap/roadmap-user-keys.md`: a user's cluster key is
//! derived from their password with it (the first 32 bytes are the Ed25519
//! seed), and so is the version-2 `/etc/shadow` hash, so both cost a guesser
//! the same slow function.
//!
//! The iteration count is not chosen here. It is a wire constant every node
//! must agree on forever (the plan fixed 210,000 from a measurement on the
//! slowest guest), and it lives in `ninep-abi` from step 5. This takes it as a
//! parameter, and as a [`NonZeroU32`]: RFC 8018 requires a positive count, and a
//! count of zero would return the salt's MAC, not a derivation, so it cannot be
//! written.
//!
//! ## One iteration is two compressions
//!
//! The HMAC's inner and outer hashes are primed with the key pads once
//! (`hmac::primed_pads`) and copied per iteration, so each `U_j = HMAC(P,
//! U_{j-1})` costs the inner hash's single block (`U_{j-1}` and its padding fit
//! in 128 bytes) and the outer's. That is the figure the count was chosen from.
//!
//! ## What this does not do
//!
//! It does not wipe. Nothing in this crate does: the key-derived pad states and
//! the running block live on the caller's stack until overwritten, and clearing
//! secrets is the job of the code that holds them (the plan gives it to `login`,
//! which wipes its copy of the key, and to `netd`, which wipes held keys).

use core::num::NonZeroU32;

use crate::hmac::{primed_pads, HMAC_LEN};
use crate::sha512::Sha512;

/// One HMAC from the primed pads: the message `parts`, in order.
#[inline(always)]
fn mac(inner: &Sha512, outer: &Sha512, parts: &[&[u8]]) -> [u8; HMAC_LEN] {
    let mut i = inner.clone();
    for p in parts {
        i.update(p);
    }
    let mut o = outer.clone();
    o.update(&i.finalize());
    o.finalize()
}

/// Fill `out` with PBKDF2-HMAC-SHA-512 of `password` and `salt` at
/// `iterations`. Any output length; each 64-byte block is RFC 8018's `F` with
/// the block index counted from 1, and the last is truncated to fit.
///
/// A password longer than 128 bytes is hashed first, as HMAC requires, so
/// every length is accepted.
///
/// # Panics
///
/// On an output longer than `(2^32 - 1) * 64` bytes, which RFC 8018 section
/// 5.2 step 1 makes an error ("derived key too long"): past it the 32-bit block
/// index would wrap and the output would repeat. No caller comes near it; the
/// assert states the precondition rather than a comment.
pub fn pbkdf2_hmac_sha512(password: &[u8], salt: &[u8], iterations: NonZeroU32, out: &mut [u8]) {
    assert!(out.len() / HMAC_LEN < u32::MAX as usize, "PBKDF2: derived key too long");
    let (inner, outer) = primed_pads(password);
    for (i, chunk) in out.chunks_mut(HMAC_LEN).enumerate() {
        // INT(i): the block index, 32-bit big-endian, from 1. The assert
        // above keeps it below 2^32.
        let index = (i as u32 + 1).to_be_bytes();
        let mut u = mac(&inner, &outer, &[salt, &index]);
        let mut t = u;
        for _ in 1..iterations.get() {
            u = mac(&inner, &outer, &[&u]);
            for k in 0..HMAC_LEN {
                t[k] ^= u[k];
            }
        }
        chunk.copy_from_slice(&t[..chunk.len()]);
    }
}

#[cfg(test)]
mod tests {
    //! Every expected value came from `scripts/gen-pbkdf2-vectors.py`, which
    //! asks Python's `hashlib.pbkdf2_hmac` (OpenSSL underneath), not this code.
    use super::*;

    // Generated by scripts/gen-pbkdf2-vectors.py (hashlib.pbkdf2_hmac); do not edit.
    // (name, password hex, salt hex, iterations, derived key hex)
    const VECTORS: &[(&str, &str, &str, u32, &str)] = &[
        ("one_iteration", "70617373776f7264", "73616c74", 1, "867f70cf1ade02cff3752599a3a53dc4af34c7a669815ae5d513554e1c8cf252c02d470a285a0501bad999bfe943c08f050235d7d68b1da55e63f73b60a57fce"),
        ("two_iterations", "70617373776f7264", "73616c74", 2, "e1d9c16aa681708a45f5c7c4e215ceb66e011a2e9f0040713f18aefdb866d53cf76cab2868a39b9f7840edce4fef5a82be67335c77a6068e04112754f27ccf4e"),
        ("c_4096", "70617373776f7264", "73616c74", 4096, "d197b1b33db0143e018b12f3d1d1479e6cdebdcc97c5c0f87f6902e072f457b5143f30602641b3d55cd335988cb36b84376060ecd532e039b742a239434af2d5"),
        ("dk_32_the_seed", "70617373776f7264", "73616c74", 2, "e1d9c16aa681708a45f5c7c4e215ceb66e011a2e9f0040713f18aefdb866d53c"),
        ("dk_65_second_block_truncated", "70617373776f7264", "73616c74", 2, "e1d9c16aa681708a45f5c7c4e215ceb66e011a2e9f0040713f18aefdb866d53cf76cab2868a39b9f7840edce4fef5a82be67335c77a6068e04112754f27ccf4e47"),
        ("dk_128_two_blocks", "70617373776f7264", "73616c74", 2, "e1d9c16aa681708a45f5c7c4e215ceb66e011a2e9f0040713f18aefdb866d53cf76cab2868a39b9f7840edce4fef5a82be67335c77a6068e04112754f27ccf4e473e311ad827b68945f4e2dddb204c78e40e2495141e411cd272d020640d673cd34aa29f1e03c579d247bf63f041156031e0bf2e841c553c530933b48c40c865"),
        ("empty_password", "", "73616c74", 2, "cc5eacbb057f2a5982fce67bf70f79fccf4adf285f5cbae1a5a1c5df012a630a5cd035da88803f2a8b7ad7d3118025e9d848280b733c39c57a76d3fa895f244c"),
        ("empty_salt", "70617373776f7264", "", 2, "52b05e3b51893d18488808ece2a6b8bd4efcd00e48db982b03e5224d872aa5231f3e7784e08601c80f90ce44099f5be47cfac9a140b778b989ff5746b09d97ab"),
        ("password_128_one_block", "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f", "73616c74", 2, "34c9b065123bc516e7dbf6b6c3ac6e2458058f1aa2c12b4f9f4d911d55a91c8551e9b4240bbf2f39478edacae010f2626bf1ce25ea7682427cd9f07f47528ff0"),
        ("password_129_hashed_first", "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80", "73616c74", 2, "1a1debcbdf429a0a41882a69fa1947e3f1d1978ef4aa732022c8434dd54f0230878514d30251d54ce56881a2fedf6080b4a2aa18c78906c57c545d6f07fbbcd8"),
        ("binary_with_zeros", "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f2021222324252627", "000102030405060708090a0b0c0d0e0f1011121314151617", 3, "bc7c15576aefdd0a2545f0016b4368f9e59636ce05607891be576728e56ca57040953a892518c8b995104e019183997d17f7f650c98656a2d2d70590c76a554e"),
        ("the_chosen_count_210000", "75736572", "6f75726f626f726f732d646576", 210000, "63849c3e6e5c9e28994712529ecc927b6d06c60c49956790ca89fa29706efeb4ce36aff8d9087a818f62c8e176fdcb7370f8fbed114f1352ae396ba1b4eac14d"),
    ];

    /// Hex into `buf`, returning the decoded prefix.
    fn unhex<'a>(s: &str, buf: &'a mut [u8; 256]) -> &'a [u8] {
        let b = s.as_bytes();
        let n = b.len() / 2;
        assert!(n <= buf.len());
        for i in 0..n {
            buf[i] = (((b[i * 2] as char).to_digit(16).expect("hex") as u8) << 4)
                | ((b[i * 2 + 1] as char).to_digit(16).expect("hex") as u8);
        }
        &buf[..n]
    }

    fn derive(pw: &[u8], salt: &[u8], c: u32, len: usize) -> [u8; 256] {
        let mut out = [0u8; 256];
        pbkdf2_hmac_sha512(pw, salt, NonZeroU32::new(c).expect("positive"), &mut out[..len]);
        out
    }

    #[test]
    fn matches_hashlib() {
        for &(name, pw, salt, c, dk) in VECTORS {
            let (mut pb, mut sb, mut db) = ([0u8; 256], [0u8; 256], [0u8; 256]);
            let (pw, salt, dk) = (unhex(pw, &mut pb), unhex(salt, &mut sb), unhex(dk, &mut db));
            let got = derive(pw, salt, c, dk.len());
            assert_eq!(&got[..dk.len()], dk, "vector {name}");
        }
    }

    /// The step's controls, as a test: each vector must SEE a flipped bit in
    /// its password and in its salt, and an iteration count one either side.
    /// A table whose rows all passed with any of those changed would be a check
    /// that cannot fail. The 210,000 row, the count every node derives with,
    /// takes the password and salt flips like every other row; it skips only
    /// the ±1 runs, for time, since its ±1 is the same code as every other
    /// row's and they run it.
    #[test]
    fn every_vector_discriminates() {
        for &(name, pw, salt, c, dk) in VECTORS {
            let (mut pb, mut sb, mut db) = ([0u8; 256], [0u8; 256], [0u8; 256]);
            let (pw, salt, dk) = (unhex(pw, &mut pb), unhex(salt, &mut sb), unhex(dk, &mut db));
            let n = dk.len();
            if !pw.is_empty() {
                let mut p2 = [0u8; 256];
                p2[..pw.len()].copy_from_slice(pw);
                p2[0] ^= 1;
                assert_ne!(&derive(&p2[..pw.len()], salt, c, n)[..n], dk, "{name}: a flipped password bit");
            }
            if !salt.is_empty() {
                let mut s2 = [0u8; 256];
                s2[..salt.len()].copy_from_slice(salt);
                s2[salt.len() - 1] ^= 0x80;
                assert_ne!(&derive(pw, &s2[..salt.len()], c, n)[..n], dk, "{name}: a flipped salt bit");
            }
            if c > 10_000 {
                continue;
            }
            assert_ne!(&derive(pw, salt, c + 1, n)[..n], dk, "{name}: one iteration more");
            if c > 1 {
                assert_ne!(&derive(pw, salt, c - 1, n)[..n], dk, "{name}: one iteration fewer");
            }
        }
    }

    /// The seed this arc takes is the first 32 bytes of the 64-byte block, so
    /// a shorter output must be a PREFIX of a longer one, not a different
    /// derivation.
    #[test]
    fn a_shorter_output_is_a_prefix() {
        let long = derive(b"password", b"salt", 2, 128);
        for len in [1usize, 32, 63, 64, 65, 127] {
            assert_eq!(&derive(b"password", b"salt", 2, len)[..len], &long[..len], "length {len}");
        }
    }
}
