#!/usr/bin/env python3
"""Generate PBKDF2-HMAC-SHA-512 test vectors for the `ed25519` crate.

Step 2 of docs/roadmap/roadmap-user-keys.md. There are no RFC vectors for the
SHA-512 variant (RFC 6070's are SHA-1), so the expected values come from
Python's `hashlib.pbkdf2_hmac`, which is OpenSSL's implementation underneath:
it shares no code, no pad handling and no block loop with the Rust, so a vector
it produces cannot be wrong in the same way the Rust can.

Prints the Rust table that `ed25519/src/pbkdf2.rs`'s tests paste in verbatim.
Regenerate with:

    python3 scripts/gen-pbkdf2-vectors.py

and `--check` (run by `make test`) confirms the checked-in table, and the two
rows `/bin/edtest` carries, are still this script's answers.

The cases are chosen where a PBKDF2 goes wrong if it goes wrong:

- the iteration count at 1 (U_1 alone), 2 (the first XOR), a few thousand, and
  210,000, the count the plan fixed for every node (a wire constant forever);
- the output length at 32 (the Ed25519 seed this arc takes), 64 (one block),
  65 (a second block, truncated) and 128 (two whole blocks), since the block
  counter INT(i) is only exercised past the first block;
- the password at 128 bytes (one HMAC block, used as the key directly) and 129
  (longer than a block, so RFC 2104 hashes it first), an empty password and an
  empty salt, and binary bytes including zeros in both.
"""
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# RFC 2104's key handling is the one place PBKDF2 inherits a length rule, so
# the two sides of it are named rather than left to a random length.
BINARY = bytes(range(256))

CASES = [
    # (name, password, salt, iterations, dk_len)
    ("one_iteration", b"password", b"salt", 1, 64),
    ("two_iterations", b"password", b"salt", 2, 64),
    ("c_4096", b"password", b"salt", 4096, 64),
    ("dk_32_the_seed", b"password", b"salt", 2, 32),
    ("dk_65_second_block_truncated", b"password", b"salt", 2, 65),
    ("dk_128_two_blocks", b"password", b"salt", 2, 128),
    ("empty_password", b"", b"salt", 2, 64),
    ("empty_salt", b"password", b"", 2, 64),
    ("password_128_one_block", BINARY[:128], b"salt", 2, 64),
    ("password_129_hashed_first", BINARY[:129], b"salt", 2, 64),
    ("binary_with_zeros", BINARY[:40], BINARY[:24], 3, 64),
    ("the_chosen_count_210000", b"user", b"ouroboros-dev", 210_000, 64),
]


def table():
    """The Rust table, as the lines pbkdf2.rs holds."""
    lines = [
        "    // Generated by scripts/gen-pbkdf2-vectors.py (hashlib.pbkdf2_hmac); do not edit.",
        "    // (name, password hex, salt hex, iterations, derived key hex)",
        "    const VECTORS: &[(&str, &str, &str, u32, &str)] = &[",
    ]
    for name, pw, salt, c, dk_len in CASES:
        dk = hashlib.pbkdf2_hmac("sha512", pw, salt, c, dk_len)
        assert len(dk) == dk_len
        lines.append(f'        ("{name}", "{pw.hex()}", "{salt.hex()}", {c}, "{dk.hex()}"),')
    lines.append("    ];")
    return lines


def edtest_array(src, name):
    """The bytes of `const <name>: [u8; 64] = [ ... ];` in edtest's source."""
    m = re.search(rf"const {name}: \[u8; 64\] = \[(.*?)\];", src, re.S)
    if not m:
        return None
    return bytes(int(x, 16) for x in re.findall(r"0x([0-9a-f]{2})", m.group(1)))


def check():
    """THE COPIES, COMPUTED RATHER THAN TRUSTED. The table in pbkdf2.rs says
    "do not edit", and edtest carries two of its rows as byte arrays; nothing
    else would notice a hand edit, or a CASES change never pasted, and the
    foreign-observer guarantee would rest on a paste nobody re-checks. Run by
    `make test`. Returns the problems found."""
    problems = []
    rs = open(os.path.join(ROOT, "ed25519/src/pbkdf2.rs")).read().splitlines()
    want = table()
    try:
        start = rs.index(want[0])
        got = rs[start:start + len(want)]
    except ValueError:
        got = []
    if got != want:
        problems.append("ed25519/src/pbkdf2.rs: the VECTORS table differs from this script's output "
                        "(regenerate it with scripts/gen-pbkdf2-vectors.py)")
    ed = open(os.path.join(ROOT, "programs/shellutils/edtest/src/main.rs")).read()
    count = re.search(r"const PBKDF2_COUNT: NonZeroU32 = nonzero\(([0-9_]+)\);", ed)
    if not count:
        problems.append("edtest: PBKDF2_COUNT not found (renamed?)")
        return problems
    count = int(count.group(1).replace("_", ""))
    for name, pw, salt, c in (("PBKDF2_V2", b"password", b"salt", 2),
                              ("PBKDF2_V210", b"user", b"ouroboros-dev", count)):
        got = edtest_array(ed, name)
        exp = hashlib.pbkdf2_hmac("sha512", pw, salt, c, 64)
        if got != exp:
            problems.append(f"edtest: {name} is not hashlib's answer for {pw!r}/{salt!r} at {c} iterations")
    return problems


def main():
    if "--check" in sys.argv:
        problems = check()
        if problems:
            print("gen-pbkdf2-vectors --check: DISAGREEMENT")
            print("\n".join(f"  - {p}" for p in problems))
            sys.exit(1)
        print(f"gen-pbkdf2-vectors: the crate's {len(CASES)} vectors and edtest's two are hashlib's answers")
        return
    print("\n".join(table()))


if __name__ == "__main__":
    main()
