#!/usr/bin/env python3
"""Generate PBKDF2-HMAC-SHA-512 test vectors for the `ed25519` crate.

Step 2 of docs/roadmap/roadmap-user-keys.md. There are no RFC vectors for the
SHA-512 variant (RFC 6070's are SHA-1), so the expected values come from
Python's `hashlib.pbkdf2_hmac`, which is OpenSSL's implementation underneath:
it shares no code, no pad handling and no block loop with the Rust, so a vector
it produces cannot be wrong in the same way the Rust can.

Prints the Rust table that `ed25519/src/pbkdf2.rs`'s tests paste in verbatim.
Regenerate with:

    python3 scripts/gen-pbkdf2-vectors.py

The cases are chosen where a PBKDF2 goes wrong if it goes wrong:

- the iteration count at 1 (U_1 alone), 2 (the first XOR), a few thousand, and
  210,000, the count the plan fixed for every node (a wire constant forever);
- the output length at 32 (the Ed25519 seed this arc takes), 64 (one block),
  65 (a second block, truncated) and 128 (two whole blocks), since the block
  counter INT(i) is only exercised past the first block;
- the password at 128 bytes (one HMAC block, used as the key directly) and 129
  (longer than a block, so RFC 2104 hashes it first), an empty password and an
  empty salt, and binary bytes including zeros in both.
"""
import hashlib

# RFC 2104's key handling is the one place PBKDF2 inherits a length rule, so
# the two sides of it are named rather than left to a random length.
BINARY = bytes(range(256))

CASES = [
    # (name, password, salt, iterations, dk_len)
    ("one_iteration", b"password", b"salt", 1, 64),
    ("two_iterations", b"password", b"salt", 2, 64),
    ("c_4096", b"password", b"salt", 4096, 64),
    ("dk_32_the_seed", b"password", b"salt", 2, 32),
    ("dk_65_second_block_truncated", b"password", b"salt", 2, 65),
    ("dk_128_two_blocks", b"password", b"salt", 2, 128),
    ("empty_password", b"", b"salt", 2, 64),
    ("empty_salt", b"password", b"", 2, 64),
    ("password_128_one_block", BINARY[:128], b"salt", 2, 64),
    ("password_129_hashed_first", BINARY[:129], b"salt", 2, 64),
    ("binary_with_zeros", BINARY[:40], BINARY[:24], 3, 64),
    ("the_chosen_count_210000", b"user", b"ouroboros-dev", 210_000, 64),
]


def main():
    print("    // Generated by scripts/gen-pbkdf2-vectors.py (hashlib.pbkdf2_hmac); do not edit.")
    print("    // (name, password hex, salt hex, iterations, derived key hex)")
    print("    const VECTORS: &[(&str, &str, &str, u32, &str)] = &[")
    for name, pw, salt, c, dk_len in CASES:
        dk = hashlib.pbkdf2_hmac("sha512", pw, salt, c, dk_len)
        assert len(dk) == dk_len
        print(f'        ("{name}", "{pw.hex()}", "{salt.hex()}", {c}, "{dk.hex()}"),')
    print("    ];")


if __name__ == "__main__":
    main()
